# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build   src/LibCK2 --configuration $(buildConfiguration)
    dotnet pack    src/LibCK2 --configuration $(buildConfiguration) --no-build --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    dotnet publish src/LibCK2 --configuration $(buildConfiguration) --no-build --output $BUILD_ARTIFACTSTAGINGDIRECTORY
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'push'
#    nuGetFeedType: 'external' # Required when command == push. Options: internal, external
#    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg' # Required when command == push
#    publishFeedCredentials: 'nuget.org scorpdx'
#    #nuget.org scorpdx
#    #publishVstsFeed: # Required when command == push && NuGetFeedType == internal
#    #publishFeedCredentials: # Required when command == push && NuGetFeedType == external
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'nuget.org scorpdx'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    versioningScheme: byBuildNumber